### ISSUE TITLE
Implementing Debug Trait on Threadpools

### ISSUE THREAD

**Issue by Leo1003** [Bathtor/rust-executors#1]
I usually make my struct derive the Debug trait. This can make it easier to debug. 
But I found the threadpools in your library doesn't implement it. 
So I can't use ```#[derive(Debug)]``` on my struct... 
If there is something also doesn't or can't implement it, I think you can also do a blank Debug implementaion first. 
It's better than nothing... :grin: 
Hope to see the change soon. :+1:

**Comment by Leo1003** [comment]
After I read the docs of dependenices, I think it can easily derive Debug without the need to implement it by hand.

**Comment by Bathtor** [comment]
Ok, I looked into deriving `Debug`, and as you said it works, but I have a concern:
Some of the structures contain a `std::sync::Mutex` and I noticed that the `Debug` implementation of said mutex will actually try to lock it, in order to read through it. It won't block there, though, so it's not a huge performance impact, but I'm wondering if we want the overhead of checking an atomic (or whatever Mutex does internally) for something as simple as debug logging, which in my opinion should be relatively cheap. If not, I could just implement Debug manually and render the mutex as `Mutex { .. }` like Sender/Receiver, for example does.

Do you have any opinion on this @Leo1003 ?

**Comment by Leo1003** [comment]
I think when people debugging their codes, the performance doesn't matter. But if the field is useless when debugging, it can represent as something like ```Mutex { ... }```. 
In short, if a field may be useful, just print it out without caring for performance.

**Comment by Bathtor** [comment]
Well...it's actually a fairly important field, as it points to the actual implementation of the `ThreadPool`, instead of the handle object. So if you actually want to debug the `ThreadPool` itself, you want to know this kind of information. On the other hand, the `Debug` output will be inconsistent and timing sensitive, as the Mutex just prints `<locked>` if it can't immediately acquire a handle, which may make debugging a bit of a nuisance.
I'll just leave it in the derived form for now, and if it becomes an issue in the future, I can still go back and hide that field. Debugging output shouldn't be breaking anyone's code (I hope^^).
