### ISSUE TITLE
Core shut down already

### ISSUE THREAD

**Issue by huntc** [Bathtor/rust-executors#13]
Hi there - thanks for this library.

I'm experiencing a problem where there should be no workers running, having had some running, and then the pool goes out of scope with the following panic:

```
thread 'thread 'thread 'test tests::test_greeting ... thread 'cb-ws-pool-worker-0cb-ws-pool-worker-2cb-ws-pool-worker-1' panicked at '' panicked at '' panicked at 'Core shut down already!Core shut down already!Core shut down already!cb-ws-pool-worker-3', ', ' panicked at '', /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/executors-0.8.0/src/crossbeam_workstealing_pool.rs/Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/executors-0.8.0/src/crossbeam_workstealing_pool.rs/Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/executors-0.8.0/src/crossbeam_workstealing_pool.rs:ok::818818
:818::44Core shut down already!4444
```

Any pointers? Thanks.

(Using 0.8.0)

**Comment by Bathtor** [comment]
Hmm, can you show me how you are shutting it down? Usually this happens if you don't shut it down properly before dropping the last pool reference.

It also isn't necessarily a problem. It just means a worker was trying to run its run loop after the core was deallocated already. So if you aren't losing any work that should have been done in the process, you could theoretically ignore it, unless you have to run with panic=abort. It's just a very brutal way of making sure no pool threads end up orphaned.

**Comment by huntc** [comment]
Thanks for replying so quickly. I’m not in front of the code at the mo, but I’m not doing anything specific to shut the pool down. Should I be, other than letting the pool go out of scope? I didn’t see a specific method to call...

**Comment by Bathtor** [comment]
Yes, if you want to clean things up nicely, you should call either `shutdown()` or `shutdown_async()` on the pool before letting it go out of scope. This is so you can control *where* you incur the cost of an orderly shutdown, instead of just happening wherever you happen to drop the last reference to the pool.

**Comment by huntc** [comment]
So sorry that I missed that. I’ll close this. Thanks again.
